modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="reds_guns"
version="1.0.0"
displayName="Red's Gun's"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="rocky, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.reds_guns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



